//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRS.IDE.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRS.IDE.Resource.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Rom Suite.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Générer le projet.
        /// </summary>
        internal static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options de génération....
        /// </summary>
        internal static string BuildOptions {
            get {
                return ResourceManager.GetString("BuildOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choix d&apos;émulateur.
        /// </summary>
        internal static string ChooseEmul {
            get {
                return ResourceManager.GetString("ChooseEmul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vraiment supprimer cette Table (TBL) ?.
        /// </summary>
        internal static string ConfirmationSuppressionTBL {
            get {
                return ResourceManager.GetString("ConfirmationSuppressionTBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couper.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string DialogueDefault_Close {
            get {
                return ResourceManager.GetString("DialogueDefault_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string DialogueDefault_OK {
            get {
                return ResourceManager.GetString("DialogueDefault_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorateur de projets.
        /// </summary>
        internal static string DockingExplorateurProjet {
            get {
                return ResourceManager.GetString("DockingExplorateurProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperçu hexadécimale (TBL).
        /// </summary>
        internal static string DockingHexaFileShow {
            get {
                return ResourceManager.GetString("DockingHexaFileShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortie.
        /// </summary>
        internal static string DockingOut {
            get {
                return ResourceManager.GetString("DockingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriétés.
        /// </summary>
        internal static string DockingPropriétés {
            get {
                return ResourceManager.GetString("DockingPropriétés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des tâches.
        /// </summary>
        internal static string DockingTaskList {
            get {
                return ResourceManager.GetString("DockingTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string Erreur {
            get {
                return ResourceManager.GetString("Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier enregistré avec succès.
        /// </summary>
        internal static string FileSaveMSG {
            get {
                return ResourceManager.GetString("FileSaveMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string FormBookMarkManager_Delete {
            get {
                return ResourceManager.GetString("FormBookMarkManager_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vraiment supprimer ce favoris ?.
        /// </summary>
        internal static string FormBookMarkManager_DeleteMessage {
            get {
                return ResourceManager.GetString("FormBookMarkManager_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste de favoris.
        /// </summary>
        internal static string FormBookMarkManager_FAVORIS {
            get {
                return ResourceManager.GetString("FormBookMarkManager_FAVORIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestions des favoris.
        /// </summary>
        internal static string FormBookMarkManager_Title {
            get {
                return ResourceManager.GetString("FormBookMarkManager_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer tous les informations requise pour la création de votre projet..
        /// </summary>
        internal static string FormNewProjet_CreateEnterAllInfo {
            get {
                return ResourceManager.GetString("FormNewProjet_CreateEnterAllInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer le projet.
        /// </summary>
        internal static string FormNewProjet_CreateProject {
            get {
                return ResourceManager.GetString("FormNewProjet_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez le dossier pour votre projet..
        /// </summary>
        internal static string FormNewProjet_FolderDialogProjectPath {
            get {
                return ResourceManager.GetString("FormNewProjet_FolderDialogProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string FormNewProjet_Options {
            get {
                return ResourceManager.GetString("FormNewProjet_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations sur le projet.
        /// </summary>
        internal static string FormNewProjet_ProjectInfo {
            get {
                return ResourceManager.GetString("FormNewProjet_ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du projet.
        /// </summary>
        internal static string FormNewProjet_ProjectName {
            get {
                return ResourceManager.GetString("FormNewProjet_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement de base.
        /// </summary>
        internal static string FormNewProjet_ProjectPath {
            get {
                return ResourceManager.GetString("FormNewProjet_ProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de projet.
        /// </summary>
        internal static string FormNewProjet_ProjectType {
            get {
                return ResourceManager.GetString("FormNewProjet_ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier de Jeu.
        /// </summary>
        internal static string FormNewProjet_Rom {
            get {
                return ResourceManager.GetString("FormNewProjet_Rom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table de jeu.
        /// </summary>
        internal static string FormNewProjet_TBL {
            get {
                return ResourceManager.GetString("FormNewProjet_TBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette table de jeux contient des Favoris, voulez vous les ajouter à dans votre projet (Recommandé)?.
        /// </summary>
        internal static string FormNewProjet_TBLHaveBookMark {
            get {
                return ResourceManager.GetString("FormNewProjet_TBLHaveBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création d&apos;un nouveau projet.
        /// </summary>
        internal static string FormNewProjet_Title {
            get {
                return ResourceManager.GetString("FormNewProjet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de projet.
        /// </summary>
        internal static string FormNewProjet_TypeProjet {
            get {
                return ResourceManager.GetString("FormNewProjet_TypeProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string FormOptions_Title {
            get {
                return ResourceManager.GetString("FormOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string FormOptionsBars {
            get {
                return ResourceManager.GetString("FormOptionsBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez le nom de votre nouveau Favoris.
        /// </summary>
        internal static string InputBox_AddBookMark {
            get {
                return ResourceManager.GetString("InputBox_AddBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez la position dans le fichier sous forme hexadécimal. Example: 80c20.
        /// </summary>
        internal static string InputBox_Jumptopos {
            get {
                return ResourceManager.GetString("InputBox_Jumptopos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce fichier n&apos;est pas une ROM Super Nintendo valide pouvant être utilisé par Visual Rom Suite.
        /// </summary>
        internal static string InvalidSnesFile {
            get {
                return ResourceManager.GetString("InvalidSnesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce fichier de Table de jeu (TBL) n&apos;est pas valide.
        /// </summary>
        internal static string InvalidTBLFile {
            get {
                return ResourceManager.GetString("InvalidTBLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer l&apos;émulateur.
        /// </summary>
        internal static string LaunchEmulator {
            get {
                return ResourceManager.GetString("LaunchEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affichage.
        /// </summary>
        internal static string MenuAffichage {
            get {
                return ResourceManager.GetString("MenuAffichage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurer l&apos;interface par défaut.
        /// </summary>
        internal static string MenuAffichageDefaultInterface {
            get {
                return ResourceManager.GetString("MenuAffichageDefaultInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Explorateur de projets.
        /// </summary>
        internal static string MenuAffichageExplorateurProjet {
            get {
                return ResourceManager.GetString("MenuAffichageExplorateurProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperçu hexadécimal.
        /// </summary>
        internal static string MenuAffichageHexaFileShow {
            get {
                return ResourceManager.GetString("MenuAffichageHexaFileShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Propriétés.
        /// </summary>
        internal static string MenuAffichagePropriétés {
            get {
                return ResourceManager.GetString("MenuAffichagePropriétés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortie.
        /// </summary>
        internal static string MenuAffichageSortie {
            get {
                return ResourceManager.GetString("MenuAffichageSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des tâches.
        /// </summary>
        internal static string MenuAffichageTaskList {
            get {
                return ResourceManager.GetString("MenuAffichageTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Aides.
        /// </summary>
        internal static string MenuAides {
            get {
                return ResourceManager.GetString("MenuAides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoris.
        /// </summary>
        internal static string MenuBookMark {
            get {
                return ResourceManager.GetString("MenuBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organiser les favoris.
        /// </summary>
        internal static string MenuBookMarkGestionnaire {
            get {
                return ResourceManager.GetString("MenuBookMarkGestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edition.
        /// </summary>
        internal static string MenuEdition {
            get {
                return ResourceManager.GetString("MenuEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fichier.
        /// </summary>
        internal static string MenuFichier {
            get {
                return ResourceManager.GetString("MenuFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enregistrer.
        /// </summary>
        internal static string MenuFichierEnregistrer {
            get {
                return ResourceManager.GetString("MenuFichierEnregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer &amp;Sous....
        /// </summary>
        internal static string MenuFichierEnregistrerSous {
            get {
                return ResourceManager.GetString("MenuFichierEnregistrerSous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer &amp;Tous/Projet.
        /// </summary>
        internal static string MenuFichierEnregistrerTous {
            get {
                return ResourceManager.GetString("MenuFichierEnregistrerTous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string MenuFichierFermer {
            get {
                return ResourceManager.GetString("MenuFichierFermer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer Tous/Projet.
        /// </summary>
        internal static string MenuFichierFermerTous {
            get {
                return ResourceManager.GetString("MenuFichierFermerTous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Nouveau.
        /// </summary>
        internal static string MenuFichierNouveau {
            get {
                return ResourceManager.GetString("MenuFichierNouveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fichier....
        /// </summary>
        internal static string MenuFichierNouveauFichier {
            get {
                return ResourceManager.GetString("MenuFichierNouveauFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Projet....
        /// </summary>
        internal static string MenuFichierNouveauProjet {
            get {
                return ResourceManager.GetString("MenuFichierNouveauProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ouvrir.
        /// </summary>
        internal static string MenuFichierOuvrir {
            get {
                return ResourceManager.GetString("MenuFichierOuvrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fichier.
        /// </summary>
        internal static string MenuFichierOuvrirFichier {
            get {
                return ResourceManager.GetString("MenuFichierOuvrirFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Projet....
        /// </summary>
        internal static string MenuFichierOuvrirProjet {
            get {
                return ResourceManager.GetString("MenuFichierOuvrirProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quitter.
        /// </summary>
        internal static string MenuFichierQuitter {
            get {
                return ResourceManager.GetString("MenuFichierQuitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Générer.
        /// </summary>
        internal static string MenuGénérer {
            get {
                return ResourceManager.GetString("MenuGénérer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de Visual Rom Suite ....
        /// </summary>
        internal static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Outils.
        /// </summary>
        internal static string MenuOutils {
            get {
                return ResourceManager.GetString("MenuOutils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un fichier Table (TBL).
        /// </summary>
        internal static string MenuProjectAddTBL {
            get {
                return ResourceManager.GetString("MenuProjectAddTBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Projet.
        /// </summary>
        internal static string MenuProjet {
            get {
                return ResourceManager.GetString("MenuProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options....
        /// </summary>
        internal static string MenuToolsOptions {
            get {
                return ResourceManager.GetString("MenuToolsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRSThingy.
        /// </summary>
        internal static string MenuToolsOptionsVRSThingy {
            get {
                return ResourceManager.GetString("MenuToolsOptionsVRSThingy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau Projet.
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir le fichier Table (TBL) à ajouter.
        /// </summary>
        internal static string OpenDialog_AddTBLTitle {
            get {
                return ResourceManager.GetString("OpenDialog_AddTBLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet Visual Rom Suite|*.vrsproj.
        /// </summary>
        internal static string OpenDialog_OpenProjectFilter {
            get {
                return ResourceManager.GetString("OpenDialog_OpenProjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir le fichier de projet à ouvrir.
        /// </summary>
        internal static string OpenDialog_OpenProjectTitle {
            get {
                return ResourceManager.GetString("OpenDialog_OpenProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers Super Nintendo (supporté)|*.smc;*.swc;*.fig;*.sfc|Tous les Fichiers (*.*)|*.*.
        /// </summary>
        internal static string OpenDialog_OpenRomFilter {
            get {
                return ResourceManager.GetString("OpenDialog_OpenRomFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir le fichier ROM à ouvrir.
        /// </summary>
        internal static string OpenDialog_OpenRomTitle {
            get {
                return ResourceManager.GetString("OpenDialog_OpenRomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers Table (*.tbl)|*.tbl|Tous les Fichiers (*.*)|*.*.
        /// </summary>
        internal static string OpenDialog_OpenTBLFilter {
            get {
                return ResourceManager.GetString("OpenDialog_OpenTBLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir un fichier.
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coller.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un fichiers.
        /// </summary>
        internal static string popExplorer_AddFile {
            get {
                return ResourceManager.GetString("popExplorer_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Générer le IPS.
        /// </summary>
        internal static string popExplorer_Build {
            get {
                return ResourceManager.GetString("popExplorer_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nettoyer le projet.
        /// </summary>
        internal static string popExplorer_CleenProject {
            get {
                return ResourceManager.GetString("popExplorer_CleenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string popExplorer_CloseProject {
            get {
                return ResourceManager.GetString("popExplorer_CloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string popExplorer_Delete {
            get {
                return ResourceManager.GetString("popExplorer_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exécuter.
        /// </summary>
        internal static string popExplorer_Executer {
            get {
                return ResourceManager.GetString("popExplorer_Executer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction de texte.
        /// </summary>
        internal static string popExplorer_ExtractText {
            get {
                return ResourceManager.GetString("popExplorer_ExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insérer dans la rom de travail.
        /// </summary>
        internal static string popExplorer_Insert {
            get {
                return ResourceManager.GetString("popExplorer_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé un nouveau tableau à largeur Fixe.
        /// </summary>
        internal static string popExplorer_NewFixeTable {
            get {
                return ResourceManager.GetString("popExplorer_NewFixeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé un nouveau point de sauvegarde.
        /// </summary>
        internal static string popExplorer_NewSavePoint {
            get {
                return ResourceManager.GetString("popExplorer_NewSavePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir.
        /// </summary>
        internal static string popExplorer_Open {
            get {
                return ResourceManager.GetString("popExplorer_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir avec ....
        /// </summary>
        internal static string popExplorer_OpenWith {
            get {
                return ResourceManager.GetString("popExplorer_OpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimisation des DTEs.
        /// </summary>
        internal static string popExplorer_OptimizeDTE {
            get {
                return ResourceManager.GetString("popExplorer_OptimizeDTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriétés.
        /// </summary>
        internal static string popExplorer_Property {
            get {
                return ResourceManager.GetString("popExplorer_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser le projet à zéro.
        /// </summary>
        internal static string popExplorer_ReinitializeProject {
            get {
                return ResourceManager.GetString("popExplorer_ReinitializeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialisé le fichier texte.
        /// </summary>
        internal static string popExplorer_ReinitializeToZero {
            get {
                return ResourceManager.GetString("popExplorer_ReinitializeToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer le projet.
        /// </summary>
        internal static string popExplorer_SaveProject {
            get {
                return ResourceManager.GetString("popExplorer_SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche de chaînes.
        /// </summary>
        internal static string popExplorer_SearchString {
            get {
                return ResourceManager.GetString("popExplorer_SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Définir comme table par défaut.
        /// </summary>
        internal static string popExplorer_SetAsDefaultTBL {
            get {
                return ResourceManager.GetString("popExplorer_SetAsDefaultTBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider le fichier.
        /// </summary>
        internal static string popExplorer_ValidFile {
            get {
                return ResourceManager.GetString("popExplorer_ValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un Favoris.
        /// </summary>
        internal static string popHexaFileShow_AddBookMark {
            get {
                return ResourceManager.GetString("popHexaFileShow_AddBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier la position courante.
        /// </summary>
        internal static string popHexaFileShow_CopyPos {
            get {
                return ResourceManager.GetString("popHexaFileShow_CopyPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aller à la position ....
        /// </summary>
        internal static string popHexaFileShow_GotoPos {
            get {
                return ResourceManager.GetString("popHexaFileShow_GotoPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers binaires.
        /// </summary>
        internal static string ProjectExplorer_FichierHexa {
            get {
                return ResourceManager.GetString("ProjectExplorer_FichierHexa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers Tables TBL.
        /// </summary>
        internal static string ProjectExplorer_FichierTBL {
            get {
                return ResourceManager.GetString("ProjectExplorer_FichierTBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers Textes.
        /// </summary>
        internal static string ProjectExplorer_FichierTexte {
            get {
                return ResourceManager.GetString("ProjectExplorer_FichierTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet.
        /// </summary>
        internal static string ProjectExplorer_Project {
            get {
                return ResourceManager.GetString("ProjectExplorer_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Nintendo.
        /// </summary>
        internal static string ProjectTypeSuperNintendo {
            get {
                return ResourceManager.GetString("ProjectTypeSuperNintendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer tout.
        /// </summary>
        internal static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meilleur.
        /// </summary>
        internal static string StringFinder_Best {
            get {
                return ResourceManager.GetString("StringFinder_Best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        internal static string StringFinder_ColPosition {
            get {
                return ResourceManager.GetString("StringFinder_ColPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeurs.
        /// </summary>
        internal static string StringFinder_ColValue {
            get {
                return ResourceManager.GetString("StringFinder_ColValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string StringFinder_GradLabelParam {
            get {
                return ResourceManager.GetString("StringFinder_GradLabelParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grande.
        /// </summary>
        internal static string StringFinder_Huge {
            get {
                return ResourceManager.GetString("StringFinder_Huge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basse.
        /// </summary>
        internal static string StringFinder_Low {
            get {
                return ResourceManager.GetString("StringFinder_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Sensible à la case).
        /// </summary>
        internal static string StringFinder_MatchCase {
            get {
                return ResourceManager.GetString("StringFinder_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille minimale.
        /// </summary>
        internal static string StringFinder_MinLenght {
            get {
                return ResourceManager.GetString("StringFinder_MinLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune chaîne n&apos;a été trouvé en ce qui correspond à votre recherche..
        /// </summary>
        internal static string StringFinder_NoStringFound {
            get {
                return ResourceManager.GetString("StringFinder_NoStringFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualité de la recherche.
        /// </summary>
        internal static string StringFinder_Quality {
            get {
                return ResourceManager.GetString("StringFinder_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalle de recherche.
        /// </summary>
        internal static string StringFinder_Range {
            get {
                return ResourceManager.GetString("StringFinder_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petite.
        /// </summary>
        internal static string StringFinder_Small {
            get {
                return ResourceManager.GetString("StringFinder_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables de jeux.
        /// </summary>
        internal static string StringFinder_TBL {
            get {
                return ResourceManager.GetString("StringFinder_TBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte à rechercher.
        /// </summary>
        internal static string StringFinder_TextToFind {
            get {
                return ResourceManager.GetString("StringFinder_TextToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaînes trouvés.
        /// </summary>
        internal static string StringFinder_TotalItem {
            get {
                return ResourceManager.GetString("StringFinder_TotalItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche de chaînes.
        /// </summary>
        internal static string StringSearchTitle {
            get {
                return ResourceManager.GetString("StringSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string TabGroupClose {
            get {
                return ResourceManager.GetString("TabGroupClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacer vers le group suivant.
        /// </summary>
        internal static string TabGroupMoveNext {
            get {
                return ResourceManager.GetString("TabGroupMoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacer vers le group précédent.
        /// </summary>
        internal static string TabGroupMovePrevious {
            get {
                return ResourceManager.GetString("TabGroupMovePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau group Horizontal.
        /// </summary>
        internal static string TabGroupNewHorizontal {
            get {
                return ResourceManager.GetString("TabGroupNewHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau group vertical.
        /// </summary>
        internal static string TabGroupNewVertical {
            get {
                return ResourceManager.GetString("TabGroupNewVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proéminent.
        /// </summary>
        internal static string TabGroupProminent {
            get {
                return ResourceManager.GetString("TabGroupProminent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rééquilibrez.
        /// </summary>
        internal static string TabGroupRebalance {
            get {
                return ResourceManager.GetString("TabGroupRebalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction de textes.
        /// </summary>
        internal static string TextExtractorTitle {
            get {
                return ResourceManager.GetString("TextExtractorTitle", resourceCulture);
            }
        }
    }
}
