//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRS.IDE.Resource {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRS.IDE.Resource.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visual Rom Suite.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Générer le projet.
        /// </summary>
        internal static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options de génération....
        /// </summary>
        internal static string BuildOptions {
            get {
                return ResourceManager.GetString("BuildOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix d&apos;émulateur.
        /// </summary>
        internal static string ChooseEmul {
            get {
                return ResourceManager.GetString("ChooseEmul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer cette Table (TBL) ?.
        /// </summary>
        internal static string ConfirmationSuppressionTBL {
            get {
                return ResourceManager.GetString("ConfirmationSuppressionTBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copier.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couper.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        internal static string DialogueDefault_Close {
            get {
                return ResourceManager.GetString("DialogueDefault_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        internal static string DialogueDefault_OK {
            get {
                return ResourceManager.GetString("DialogueDefault_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Explorateur de projets.
        /// </summary>
        internal static string DockingExplorateurProjet {
            get {
                return ResourceManager.GetString("DockingExplorateurProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aperçu hexadécimale (TBL).
        /// </summary>
        internal static string DockingHexaFileShow {
            get {
                return ResourceManager.GetString("DockingHexaFileShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sortie.
        /// </summary>
        internal static string DockingOut {
            get {
                return ResourceManager.GetString("DockingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Propriétés.
        /// </summary>
        internal static string DockingPropriétés {
            get {
                return ResourceManager.GetString("DockingPropriétés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des tâches.
        /// </summary>
        internal static string DockingTaskList {
            get {
                return ResourceManager.GetString("DockingTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string Erreur {
            get {
                return ResourceManager.GetString("Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier enregistré avec succès.
        /// </summary>
        internal static string FileSaveMSG {
            get {
                return ResourceManager.GetString("FileSaveMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string FormBookMarkManager_Delete {
            get {
                return ResourceManager.GetString("FormBookMarkManager_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer ce favoris ?.
        /// </summary>
        internal static string FormBookMarkManager_DeleteMessage {
            get {
                return ResourceManager.GetString("FormBookMarkManager_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste de favoris.
        /// </summary>
        internal static string FormBookMarkManager_FAVORIS {
            get {
                return ResourceManager.GetString("FormBookMarkManager_FAVORIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestions des favoris.
        /// </summary>
        internal static string FormBookMarkManager_Title {
            get {
                return ResourceManager.GetString("FormBookMarkManager_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer tous les informations requise pour la création de votre projet..
        /// </summary>
        internal static string FormNewProjet_CreateEnterAllInfo {
            get {
                return ResourceManager.GetString("FormNewProjet_CreateEnterAllInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer le projet.
        /// </summary>
        internal static string FormNewProjet_CreateProject {
            get {
                return ResourceManager.GetString("FormNewProjet_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez le dossier pour votre projet..
        /// </summary>
        internal static string FormNewProjet_FolderDialogProjectPath {
            get {
                return ResourceManager.GetString("FormNewProjet_FolderDialogProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string FormNewProjet_Options {
            get {
                return ResourceManager.GetString("FormNewProjet_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur le projet.
        /// </summary>
        internal static string FormNewProjet_ProjectInfo {
            get {
                return ResourceManager.GetString("FormNewProjet_ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du projet.
        /// </summary>
        internal static string FormNewProjet_ProjectName {
            get {
                return ResourceManager.GetString("FormNewProjet_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Emplacement de base.
        /// </summary>
        internal static string FormNewProjet_ProjectPath {
            get {
                return ResourceManager.GetString("FormNewProjet_ProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de projet.
        /// </summary>
        internal static string FormNewProjet_ProjectType {
            get {
                return ResourceManager.GetString("FormNewProjet_ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier de Jeu.
        /// </summary>
        internal static string FormNewProjet_Rom {
            get {
                return ResourceManager.GetString("FormNewProjet_Rom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table de jeu.
        /// </summary>
        internal static string FormNewProjet_TBL {
            get {
                return ResourceManager.GetString("FormNewProjet_TBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette table de jeux contient des Favoris, voulez vous les ajouter à dans votre projet (Recommandé)?.
        /// </summary>
        internal static string FormNewProjet_TBLHaveBookMark {
            get {
                return ResourceManager.GetString("FormNewProjet_TBLHaveBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un nouveau projet.
        /// </summary>
        internal static string FormNewProjet_Title {
            get {
                return ResourceManager.GetString("FormNewProjet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de projet.
        /// </summary>
        internal static string FormNewProjet_TypeProjet {
            get {
                return ResourceManager.GetString("FormNewProjet_TypeProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string FormOptions_Title {
            get {
                return ResourceManager.GetString("FormOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string FormOptionsBars {
            get {
                return ResourceManager.GetString("FormOptionsBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le nom de votre nouveau Favoris.
        /// </summary>
        internal static string InputBox_AddBookMark {
            get {
                return ResourceManager.GetString("InputBox_AddBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez la position dans le fichier sous forme hexadécimal. Example: 80c20.
        /// </summary>
        internal static string InputBox_Jumptopos {
            get {
                return ResourceManager.GetString("InputBox_Jumptopos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce fichier n&apos;est pas une ROM Super Nintendo valide pouvant être utilisé par Visual Rom Suite.
        /// </summary>
        internal static string InvalidSnesFile {
            get {
                return ResourceManager.GetString("InvalidSnesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce fichier de Table de jeu (TBL) n&apos;est pas valide.
        /// </summary>
        internal static string InvalidTBLFile {
            get {
                return ResourceManager.GetString("InvalidTBLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrer l&apos;émulateur.
        /// </summary>
        internal static string LaunchEmulator {
            get {
                return ResourceManager.GetString("LaunchEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage.
        /// </summary>
        internal static string MenuAffichage {
            get {
                return ResourceManager.GetString("MenuAffichage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restaurer l&apos;interface par défaut.
        /// </summary>
        internal static string MenuAffichageDefaultInterface {
            get {
                return ResourceManager.GetString("MenuAffichageDefaultInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Explorateur de projets.
        /// </summary>
        internal static string MenuAffichageExplorateurProjet {
            get {
                return ResourceManager.GetString("MenuAffichageExplorateurProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aperçu hexadécimal.
        /// </summary>
        internal static string MenuAffichageHexaFileShow {
            get {
                return ResourceManager.GetString("MenuAffichageHexaFileShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Propriétés.
        /// </summary>
        internal static string MenuAffichagePropriétés {
            get {
                return ResourceManager.GetString("MenuAffichagePropriétés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sortie.
        /// </summary>
        internal static string MenuAffichageSortie {
            get {
                return ResourceManager.GetString("MenuAffichageSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des tâches.
        /// </summary>
        internal static string MenuAffichageTaskList {
            get {
                return ResourceManager.GetString("MenuAffichageTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Aides.
        /// </summary>
        internal static string MenuAides {
            get {
                return ResourceManager.GetString("MenuAides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Favoris.
        /// </summary>
        internal static string MenuBookMark {
            get {
                return ResourceManager.GetString("MenuBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Organiser les favoris.
        /// </summary>
        internal static string MenuBookMarkGestionnaire {
            get {
                return ResourceManager.GetString("MenuBookMarkGestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Edition.
        /// </summary>
        internal static string MenuEdition {
            get {
                return ResourceManager.GetString("MenuEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Fichier.
        /// </summary>
        internal static string MenuFichier {
            get {
                return ResourceManager.GetString("MenuFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Enregistrer.
        /// </summary>
        internal static string MenuFichierEnregistrer {
            get {
                return ResourceManager.GetString("MenuFichierEnregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer &amp;Sous....
        /// </summary>
        internal static string MenuFichierEnregistrerSous {
            get {
                return ResourceManager.GetString("MenuFichierEnregistrerSous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer &amp;Tous/Projet.
        /// </summary>
        internal static string MenuFichierEnregistrerTous {
            get {
                return ResourceManager.GetString("MenuFichierEnregistrerTous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        internal static string MenuFichierFermer {
            get {
                return ResourceManager.GetString("MenuFichierFermer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer Tous/Projet.
        /// </summary>
        internal static string MenuFichierFermerTous {
            get {
                return ResourceManager.GetString("MenuFichierFermerTous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Nouveau.
        /// </summary>
        internal static string MenuFichierNouveau {
            get {
                return ResourceManager.GetString("MenuFichierNouveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Fichier....
        /// </summary>
        internal static string MenuFichierNouveauFichier {
            get {
                return ResourceManager.GetString("MenuFichierNouveauFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Projet....
        /// </summary>
        internal static string MenuFichierNouveauProjet {
            get {
                return ResourceManager.GetString("MenuFichierNouveauProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Ouvrir.
        /// </summary>
        internal static string MenuFichierOuvrir {
            get {
                return ResourceManager.GetString("MenuFichierOuvrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Fichier.
        /// </summary>
        internal static string MenuFichierOuvrirFichier {
            get {
                return ResourceManager.GetString("MenuFichierOuvrirFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Projet....
        /// </summary>
        internal static string MenuFichierOuvrirProjet {
            get {
                return ResourceManager.GetString("MenuFichierOuvrirProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Quitter.
        /// </summary>
        internal static string MenuFichierQuitter {
            get {
                return ResourceManager.GetString("MenuFichierQuitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Générer.
        /// </summary>
        internal static string MenuGénérer {
            get {
                return ResourceManager.GetString("MenuGénérer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos de Visual Rom Suite ....
        /// </summary>
        internal static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Outils.
        /// </summary>
        internal static string MenuOutils {
            get {
                return ResourceManager.GetString("MenuOutils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un fichier Table (TBL).
        /// </summary>
        internal static string MenuProjectAddTBL {
            get {
                return ResourceManager.GetString("MenuProjectAddTBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Projet.
        /// </summary>
        internal static string MenuProjet {
            get {
                return ResourceManager.GetString("MenuProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Options....
        /// </summary>
        internal static string MenuToolsOptions {
            get {
                return ResourceManager.GetString("MenuToolsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VRSThingy.
        /// </summary>
        internal static string MenuToolsOptionsVRSThingy {
            get {
                return ResourceManager.GetString("MenuToolsOptionsVRSThingy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau Projet.
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir le fichier Table (TBL) à ajouter.
        /// </summary>
        internal static string OpenDialog_AddTBLTitle {
            get {
                return ResourceManager.GetString("OpenDialog_AddTBLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projet Visual Rom Suite|*.vrsproj.
        /// </summary>
        internal static string OpenDialog_OpenProjectFilter {
            get {
                return ResourceManager.GetString("OpenDialog_OpenProjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir le fichier de projet à ouvrir.
        /// </summary>
        internal static string OpenDialog_OpenProjectTitle {
            get {
                return ResourceManager.GetString("OpenDialog_OpenProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichiers Super Nintendo (supporté)|*.smc;*.swc;*.fig;*.sfc|Tous les Fichiers (*.*)|*.*.
        /// </summary>
        internal static string OpenDialog_OpenRomFilter {
            get {
                return ResourceManager.GetString("OpenDialog_OpenRomFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir le fichier ROM à ouvrir.
        /// </summary>
        internal static string OpenDialog_OpenRomTitle {
            get {
                return ResourceManager.GetString("OpenDialog_OpenRomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichiers Table (*.tbl)|*.tbl|Tous les Fichiers (*.*)|*.*.
        /// </summary>
        internal static string OpenDialog_OpenTBLFilter {
            get {
                return ResourceManager.GetString("OpenDialog_OpenTBLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir un fichier.
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coller.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un fichiers.
        /// </summary>
        internal static string popExplorer_AddFile {
            get {
                return ResourceManager.GetString("popExplorer_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Générer le IPS.
        /// </summary>
        internal static string popExplorer_Build {
            get {
                return ResourceManager.GetString("popExplorer_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nettoyer le projet.
        /// </summary>
        internal static string popExplorer_CleenProject {
            get {
                return ResourceManager.GetString("popExplorer_CleenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        internal static string popExplorer_CloseProject {
            get {
                return ResourceManager.GetString("popExplorer_CloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string popExplorer_Delete {
            get {
                return ResourceManager.GetString("popExplorer_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécuter.
        /// </summary>
        internal static string popExplorer_Executer {
            get {
                return ResourceManager.GetString("popExplorer_Executer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extraction de texte.
        /// </summary>
        internal static string popExplorer_ExtractText {
            get {
                return ResourceManager.GetString("popExplorer_ExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insérer dans la rom de travail.
        /// </summary>
        internal static string popExplorer_Insert {
            get {
                return ResourceManager.GetString("popExplorer_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé un nouveau tableau à largeur Fixe.
        /// </summary>
        internal static string popExplorer_NewFixeTable {
            get {
                return ResourceManager.GetString("popExplorer_NewFixeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé un nouveau point de sauvegarde.
        /// </summary>
        internal static string popExplorer_NewSavePoint {
            get {
                return ResourceManager.GetString("popExplorer_NewSavePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir.
        /// </summary>
        internal static string popExplorer_Open {
            get {
                return ResourceManager.GetString("popExplorer_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir avec ....
        /// </summary>
        internal static string popExplorer_OpenWith {
            get {
                return ResourceManager.GetString("popExplorer_OpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optimisation des DTEs.
        /// </summary>
        internal static string popExplorer_OptimizeDTE {
            get {
                return ResourceManager.GetString("popExplorer_OptimizeDTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Propriétés.
        /// </summary>
        internal static string popExplorer_Property {
            get {
                return ResourceManager.GetString("popExplorer_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réinitialiser le projet à zéro.
        /// </summary>
        internal static string popExplorer_ReinitializeProject {
            get {
                return ResourceManager.GetString("popExplorer_ReinitializeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réinitialisé le fichier texte.
        /// </summary>
        internal static string popExplorer_ReinitializeToZero {
            get {
                return ResourceManager.GetString("popExplorer_ReinitializeToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer le projet.
        /// </summary>
        internal static string popExplorer_SaveProject {
            get {
                return ResourceManager.GetString("popExplorer_SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche de chaînes.
        /// </summary>
        internal static string popExplorer_SearchString {
            get {
                return ResourceManager.GetString("popExplorer_SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Définir comme table par défaut.
        /// </summary>
        internal static string popExplorer_SetAsDefaultTBL {
            get {
                return ResourceManager.GetString("popExplorer_SetAsDefaultTBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider le fichier.
        /// </summary>
        internal static string popExplorer_ValidFile {
            get {
                return ResourceManager.GetString("popExplorer_ValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un Favoris.
        /// </summary>
        internal static string popHexaFileShow_AddBookMark {
            get {
                return ResourceManager.GetString("popHexaFileShow_AddBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copier la position courante.
        /// </summary>
        internal static string popHexaFileShow_CopyPos {
            get {
                return ResourceManager.GetString("popHexaFileShow_CopyPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aller à la position ....
        /// </summary>
        internal static string popHexaFileShow_GotoPos {
            get {
                return ResourceManager.GetString("popHexaFileShow_GotoPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projet.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichiers binaires.
        /// </summary>
        internal static string ProjectExplorer_FichierHexa {
            get {
                return ResourceManager.GetString("ProjectExplorer_FichierHexa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichiers Tables TBL.
        /// </summary>
        internal static string ProjectExplorer_FichierTBL {
            get {
                return ResourceManager.GetString("ProjectExplorer_FichierTBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichiers Textes.
        /// </summary>
        internal static string ProjectExplorer_FichierTexte {
            get {
                return ResourceManager.GetString("ProjectExplorer_FichierTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projet.
        /// </summary>
        internal static string ProjectExplorer_Project {
            get {
                return ResourceManager.GetString("ProjectExplorer_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Super Nintendo.
        /// </summary>
        internal static string ProjectTypeSuperNintendo {
            get {
                return ResourceManager.GetString("ProjectTypeSuperNintendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer tout.
        /// </summary>
        internal static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Meilleur.
        /// </summary>
        internal static string StringFinder_Best {
            get {
                return ResourceManager.GetString("StringFinder_Best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Positions.
        /// </summary>
        internal static string StringFinder_ColPosition {
            get {
                return ResourceManager.GetString("StringFinder_ColPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valeurs.
        /// </summary>
        internal static string StringFinder_ColValue {
            get {
                return ResourceManager.GetString("StringFinder_ColValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        internal static string StringFinder_GradLabelParam {
            get {
                return ResourceManager.GetString("StringFinder_GradLabelParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grande.
        /// </summary>
        internal static string StringFinder_Huge {
            get {
                return ResourceManager.GetString("StringFinder_Huge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Basse.
        /// </summary>
        internal static string StringFinder_Low {
            get {
                return ResourceManager.GetString("StringFinder_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (Sensible à la case).
        /// </summary>
        internal static string StringFinder_MatchCase {
            get {
                return ResourceManager.GetString("StringFinder_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille minimale.
        /// </summary>
        internal static string StringFinder_MinLenght {
            get {
                return ResourceManager.GetString("StringFinder_MinLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune chaîne n&apos;a été trouvé en ce qui correspond à votre recherche..
        /// </summary>
        internal static string StringFinder_NoStringFound {
            get {
                return ResourceManager.GetString("StringFinder_NoStringFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qualité de la recherche.
        /// </summary>
        internal static string StringFinder_Quality {
            get {
                return ResourceManager.GetString("StringFinder_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intervalle de recherche.
        /// </summary>
        internal static string StringFinder_Range {
            get {
                return ResourceManager.GetString("StringFinder_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Petite.
        /// </summary>
        internal static string StringFinder_Small {
            get {
                return ResourceManager.GetString("StringFinder_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tables de jeux.
        /// </summary>
        internal static string StringFinder_TBL {
            get {
                return ResourceManager.GetString("StringFinder_TBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte à rechercher.
        /// </summary>
        internal static string StringFinder_TextToFind {
            get {
                return ResourceManager.GetString("StringFinder_TextToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chaînes trouvés.
        /// </summary>
        internal static string StringFinder_TotalItem {
            get {
                return ResourceManager.GetString("StringFinder_TotalItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche de chaînes.
        /// </summary>
        internal static string StringSearchTitle {
            get {
                return ResourceManager.GetString("StringSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        internal static string TabGroupClose {
            get {
                return ResourceManager.GetString("TabGroupClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déplacer vers le group suivant.
        /// </summary>
        internal static string TabGroupMoveNext {
            get {
                return ResourceManager.GetString("TabGroupMoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déplacer vers le group précédent.
        /// </summary>
        internal static string TabGroupMovePrevious {
            get {
                return ResourceManager.GetString("TabGroupMovePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau group Horizontal.
        /// </summary>
        internal static string TabGroupNewHorizontal {
            get {
                return ResourceManager.GetString("TabGroupNewHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau group vertical.
        /// </summary>
        internal static string TabGroupNewVertical {
            get {
                return ResourceManager.GetString("TabGroupNewVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proéminent.
        /// </summary>
        internal static string TabGroupProminent {
            get {
                return ResourceManager.GetString("TabGroupProminent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rééquilibrez.
        /// </summary>
        internal static string TabGroupRebalance {
            get {
                return ResourceManager.GetString("TabGroupRebalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extraction de textes.
        /// </summary>
        internal static string TextExtractorTitle {
            get {
                return ResourceManager.GetString("TextExtractorTitle", resourceCulture);
            }
        }
    }
}
